---
  - name: "move files to server"
    become: yes
    synchronize:
      src: /root/project/backend/dist
      dest: ./udapeople-circle94
      recursive: true

  - name: "move node modules"
    become: yes
    synchronize:
      src: /root/project/backend/node_modules
      dest: ./udapeople-circle94
      recursive: true

  - name: "run server"
    become: true
    command: pm2 start -f ./main.js
    args:
      chdir: ./udapeople-circle94/dist
