version: 2.1

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            cd frontend
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
             cd backend
             npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build

  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache
      - run:
          name: test-frontend
          command: |
              cd frontend
              npm audit --audit-level=critical
                
  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache
      - run:
          name: test-backend
          command: |
              cd backend
              npm audit --audit-level=critical
            
  scan-frontend:
    docker:
      # Docker image here
    steps:
      - checkout
      - restore_cache
      - run:
          name: test-backend
          command: |

workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
